name: Component Bug
description: Report a bug in a Lighthouse HLTH UI component
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        ## Component Bug Report
        Help us fix issues in the design system.

  - type: input
    id: component_name
    attributes:
      label: Component Name
      description: Which component has the bug?
      placeholder: "e.g., Button, MetricCard, DataTable"
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How severe is this bug?
      options:
        - "P0: Critical (Blocking production, accessibility violation)"
        - "P1: High (Broken functionality, poor UX)"
        - "P2: Medium (Visual issue, minor bug)"
        - "P3: Low (Polish, edge case)"
    validations:
      required: true

  - type: dropdown
    id: bug_type
    attributes:
      label: Bug Type
      description: What kind of issue is this?
      options:
        - "Visual (styling, layout)"
        - "Functional (props not working)"
        - "Accessibility (WCAG violation)"
        - "Performance (slow render, memory leak)"
        - "TypeScript (type errors)"
        - "Responsive (mobile/tablet issues)"
        - "Dark Mode (theme switching)"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: Clear description of what's broken
      placeholder: "When I use the [component] with [props], it [unexpected behavior]..."
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this bug?
      placeholder: |
        1. Import component: `import { Button } from '@lighthouse-hlth/ui'`
        2. Use with props: `<Button variant="primary" disabled />`
        3. Observe: Button shows enabled state visually
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should happen instead?
      placeholder: "Button should have opacity: 0.5 and cursor: not-allowed when disabled"
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happens?
      placeholder: "Button appears fully opaque and cursor is pointer"
    validations:
      required: true

  - type: textarea
    id: code_example
    attributes:
      label: Code Example
      description: Minimal reproduction code
      placeholder: |
        ```tsx
        <Button variant="primary" disabled onClick={() => alert('clicked')}>
          Click Me
        </Button>
        ```
      render: tsx
    validations:
      required: false

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Where did this occur?
      placeholder: |
        - Package version: @lighthouse-hlth/ui@1.2.3
        - React version: 18.2.0
        - Browser: Chrome 120.0
        - OS: macOS 14.0
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots / Screen Recording
      description: Visual evidence of the bug
      placeholder: "Drag and drop images or paste links here"
    validations:
      required: false

  - type: dropdown
    id: accessibility_impact
    attributes:
      label: Accessibility Impact
      description: Does this affect accessibility?
      options:
        - "No accessibility impact"
        - "Minor (non-critical a11y issue)"
        - "Major (WCAG AA violation)"
        - "Critical (blocks assistive tech users)"
    validations:
      required: true

  - type: textarea
    id: workaround
    attributes:
      label: Workaround
      description: Is there a temporary workaround?
      placeholder: "Can manually add disabled styles with className prop"
    validations:
      required: false
